# Site settings
title: Videogames com Cerveja
email: vgscomcerveja@gmail.com
description: >
  Nosso objetivo é compartilhar experiências e opiniões gamísticas, tanto na jogatina
  quanto no colecionismo.. E que adoramos uma cerveja!
baseurl: "/vgscomcerveja"
url: "http://felipebbarbosa.github.io"
twitter_username: vgscomcerveja
github_username:  felipebbarbosa

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
