# Site settings
title: Videogames com Cerveja
email: vgscomcerveja@gmail.com
description: >
  Nosso objetivo é compartilhar experiências e opiniões gamísticas, tanto na jogatina
  quanto no colecionismo.. E que adoramos uma cerveja!
baseurl: ""
url: "www.vgscomcerveja.com.br"
twitter_username: vgscomcerveja
github_username:  felipebbarbosa

# Build settings
markdown: kramdown

paginate: 7
paginate_path: "page:num"

gems:
  - jekyll-paginate
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
