# Site settings
title: Videogames com Cerveja
email: vgscomcerveja@gmail.com
description: >
  Um blog cujo o objetivo é compartilhar experiências e opiniões gamísticas, tanto no jogo em si quanto no colecionismo..
  E que adora uma cerveja!
baseurl: "/vgscomcerveja"
url: "www.vgscomcerveja.com.br"
twitter_username: vgscomcerveja
github_username:  felipebbarbosa

# Build settings
markdown: kramdown

paginate: 7
paginate_path: "page:num"

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
